name: Build Docker Image

on:
  workflow_call:
    secrets:
      image_name:
        description: "Docker image tag"
        required: true
      registry_url:
        description: "Docker image tag"
        required: true
      registry_password:
        description: "Docker image tag"
        required: true
      registry_username:
        description: "Docker image tag"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build application
        run: yarn build --production

      - name: Build Docker image
        run: docker build -t ${{secrets.registry_url}}/${{ secrets.image_name }} .

      - name: Configure Docker for HTTP registry
        run: |
          echo '{ "insecure-registries": ["${{ secrets.registry_url }}"] }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Log in to Docker Registry
        run: echo ${{ secrets.registry_password }} | docker login ${{ secrets.registry_url }} -u ${{ secrets.registry_username }} --password-stdin

      - name: Push Docker image to registry
        run: |
          docker tag analytics-front-main ${{ secrets.registry_url }}/${{ secrets.image_name }} 
          docker push ${{ secrets.registry_url }}/${{ secrets.image_name }} 

