name: Deploy Application

on:
  workflow_call:
    secrets:
      branch:
        description: "Current branch"
        required: true
      ssh_host:
        description: "SSH Host"
        required: true
      ssh_user:
        description: "SSH User"
        required: true
      ssh_key:
        description: "SSH Private Key"
        required: true
      registry_password:
        description: "Registry Password"
        required: true
      registry_username:
        description: "Registry Password"
        required: true
      image_name:
        description: "Container Name"
        required: true

jobs:
  # На данный момент при выполнении этого шага происходит перезагрузка (редеплой) всех стендов указанных в docker-compose.yml на сервере.
  # Необходимо "распилить" процесс редеплоя: при пуше в dev ветку собирать - dev стенд. и т.д.
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy Docker container via SSH
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.ssh_host }}
        username: ${{ secrets.ssh_user }}
        key: ${{ secrets.ssh_key }}
        script: |
            echo ${{ secrets.registry_password }} | docker login localhost:5000 -u ${{ secrets.registry_username }} --password-stdin
            docker pull localhost:5000/${{ secrets.image_name }}
            cd ~/code/configs/analytics-web
            docker compose up -d --no-deps ${{ secrets.branch }}