name: Deploy Application

on:
  workflow_call:
    inputs:
      branch:
        description: "Current branch"
        required: true
        type: string
      ssh_host:
        description: "SSH Host"
        required: true
        type: string
      ssh_user:
        description: "SSH User"
        required: true
        type: string
      ssh_key:
        description: "SSH Private Key"
        required: true
        type: string
      registry_password:
        description: "Registry Password"
        required: true
        type: string
      registry_username:
        description: "Registry Password"
        required: true
        type: string
      image_name: # analytics-front-main:latest
        description: "Container Name"
        required: true
        type: string

jobs:
  # На данный момент при выполнении этого шага происходит перезагрузка (редеплой) всех стендов указанных в docker-compose.yml на сервере.
  # Необходимо "распилить" процесс редеплоя: при пуше в dev ветку собирать - dev стенд. и т.д.
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy Docker container via SSH
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ inputs.ssh_host }}
        username: ${{ inputs.ssh_user }}
        key: ${{ inputs.ssh_key }}
        script: |
            echo ${{ inputs.registry_password }} | docker login localhost:5000 -u ${{ inputs.registry_username }} --password-stdin
            docker pull localhost:5000/${{ inputs.image_name }}
            cd ~/code/configs/analytics-web
            docker compose up -d --no-deps ${{ inputs.branch }}