name: Dev CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets:
      image_name: ${{ secrets.DEV_IMAGE_NAME }}
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
      registry_username: ${{ secrets.REGISTRY_USERNAME }}
      registry_url: ${{ secrets.DOCKER_REGISTRY }}

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    secrets:
      branch: "dev" # при изменении надо поменять название сервиса в docker-compose на сервере
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
      registry_username: ${{ secrets.REGISTRY_USERNAME }}
      ssh_host: ${{ secrets.SSH_HOST }}
      ssh_user: ${{ secrets.SSH_USER }}
      ssh_key: ${{ secrets.SSH_KEY }}
      image_name: ${{ secrets.DEV_IMAGE_NAME }}